"""Writes lib/src/i18n_en.dart from the web console's English translations.

Usage: python tool/gen_i18n.py path/to/web-admin/src/utils/i18n/en.json
"""
import json
import os
import sys


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


def main():
    src = json.load(open(sys.argv[1], encoding='utf-8'))
    out = [
        '// Generated by tool/gen_i18n.py from the web console\'s en.json. Do not edit.',
        '',
        'const Map<String, List<String>> kEnglish = {',
    ]
    for k, v in src.items():
        forms = [v['One']] + ([v['Other']] if 'Other' in v else [])
        out.append('  %s: [%s],' % (dart_str(k), ', '.join(dart_str(f) for f in forms)))
    out.append('};')
    path = os.path.join(os.path.dirname(__file__), '..', 'lib', 'src', 'i18n_en.dart')
    open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('wrote', len(src), 'strings')


if __name__ == '__main__':
    main()
